### ISSUE TITLE
Adding project to dependencies not working

### ISSUE THREAD

**Issue by kurochenko** [angelcervera/osm4scala#11]
Hi,

i've tried to add this lib as dependency to my project, but it failed to load. Could you please advise what i'm doing wrong or how to fix it? 

Dependency i've added:
```
"com.acervera.osm4scala" %% "osm4scala" % "1.0"
```

Resolvers I have:
```
resolvers ++= Seq(
  "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases",
  Resolver.jcenterRepo
)
```

Error I get:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.acervera.osm4scala#osm4scala_2.11;1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by angelcervera** [comment]
That should work, because it is in the public JCenter repository https://bintray.com/search?query=osm4scala

Anyway, I will check it today.

**Comment by angelcervera** [comment]
There is an error in the documentation.
I fixed it:
~~~
libraryDependencies += "com.acervera.osm4scala" %% "osm4scala-core" % "1.0"
~~~

There was a typo in the name of the library. IT is neccessary add the "-core" suffix. Also, added quotes.

I'm sorry. ;)

Regards.

**Comment by kurochenko** [comment]
Hi, thanks for fixing it. After trying it was still not working. When i started to investigate why i found out that i'm using scala version `2.11` though in [`jcenter.bintray`](http://jcenter.bintray.com/com/acervera/osm4scala/) repo there is artifact only for `2.10`.

In [`dl.bintray`](https://dl.bintray.com/angelcervera/maven/com/acervera/osm4scala/) though there are artifacts for both versions. But for build to work i needed to add another resolver to my `build.sbt` file: 

```
"osm3scala" at "https://dl.bintray.com/angelcervera/maven"
```

So just FYI that builds won't currently work out of the box for users with scala `2.11`.

**Comment by angelcervera** [comment]
Hi Kurochenko.
It is weird, because as you can see in my repository, I published the both version.

Just I pushed my first commit in one project [using the new release](https://github.com/angelcervera/pgrouting-fast-loader/blob/master/build.sbt) and looks like it is working without add any resolver. It is using Scala 2.11 and I clean my Ivy folder to force to download the jar from the repository.

But you are 100% right. Why in JCenter is available only the Scala 2.11 version? I will research tomorrow.

Anyway, I am going to add this information in the documentation. Maybe it is useful for other people.

Thx for your time.

**Comment by angelcervera** [comment]
Maybe  stackoverflow can help us http://stackoverflow.com/questions/40963068/jcenter-and-bintray-not-in-sync

**Comment by angelcervera** [comment]
Bintray team fixed it.
